<div class="col-sm-4">
                        <div class="f-s-box">
                            <div class="f-s-box-con">
                              
							    <div class="tit" style="background-image:url(/images/ico-fun-{dede:global name=itemindex runphp="yes"}@me=@me+1;{/dede:global}.png);">
                                  
								    <h4>{dede:field name='typename'/}</h4>
                                </div>
                                <div class="con">
                                
{dede:arclist titlelen='60' row='2'}
								 <a href="[field:arcurl/]">[field:title/]</a>

{/dede:arclist}
                                
				
                                <a href="{dede:field name='typeurl'/}" class="more-btn">了解更多</a>
                            </div>
                        </div>
                    </div>

                

                    
                </div>