<?php
$z[0]=Array("field","",286,305);
$z[0][4]['name']="title";
$z[1]=Array("global","",306,332);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",699,734);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channelartlist","\r\n                          <dl class=\"col-md-12 col-xs-6\">\r\n                            <dt>{dede:field name='typename'/}</dt>\r\n                            {dede:channel type='son' noself='yes' }\r\n                          \r\n                            <dd><a href=\"[field:typelink/]\">[field:typename/]</a></dd>\r\n							\r\n                           {/dede:channel}\r\n							\r\n                        </dl>\r\n",972,1452);
$z[3][4]['typeid']="3,4,5,6";
$z[3][4]['row']="4";
$z[4]=Array("field","",1687,1716);
$z[4][4]['name']="position";
$z[5]=Array("field","",1778,1797);
$z[5][4]['name']="title";
$z[6]=Array("field","",1880,1898);
$z[6][4]['name']="body";
$z[7]=Array("include","",2055,2092);
$z[7][4]['filename']="footer.htm";

?>