<?php
$z[0]=Array("channel","\r\n				    <li>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </li>\r\n				",608,807);
$z[0][4]['typeid']="1";
$z[0][4]['type']="son";
$z[1]=Array("channel","\r\n				    <li>\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </li>\r\n				",1059,1258);
$z[1][4]['typeid']="2";
$z[1][4]['type']="son";

?>