<?php
$z[0]=Array("field","",284,303);
$z[0][4]['name']="title";
$z[1]=Array("global","",304,330);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",693,728);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","	\r\n                    <li class=\"col-xs-4\">\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </li>\r\n                 ",1288,1526);
$z[3][4]['row']="4";
$z[3][4]['typeid']="2";
$z[4]=Array("field","",1869,1890);
$z[4][4]['name']="content";
$z[5]=Array("include","",2034,2071);
$z[5][4]['filename']="footer.htm";

?>