<?php
$z[0]=Array("field","",286,305);
$z[0][4]['name']="title";
$z[1]=Array("global","",306,332);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",695,730);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","	\r\n                    <li class=\"col-xs-4\">\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </li>\r\n                 ",1290,1528);
$z[3][4]['row']="4";
$z[3][4]['typeid']="2";
$z[4]=Array("field","",1871,1892);
$z[4][4]['name']="content";
$z[5]=Array("include","",2036,2073);
$z[5][4]['filename']="footer.htm";

?>