<?php
$z[0]=Array("field","",287,306);
$z[0][4]['name']="title";
$z[1]=Array("global","",307,333);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",696,731);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","	\r\n                    <li class=\"col-xs-4\">\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </li>\r\n                 ",1304,1542);
$z[3][4]['row']="4";
$z[3][4]['typeid']="2";
$z[4]=Array("list","\r\n						<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                         ",1832,1957);
$z[4][4]['pagesize']="8";
$z[5]=Array("pagelist","",2257,2338);
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="3";
$z[6]=Array("include","",2765,2802);
$z[6][4]['filename']="footer.htm";

?>