<?php
$z[0]=Array("field","",285,304);
$z[0][4]['name']="title";
$z[1]=Array("global","",305,331);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",694,729);
$z[2][4]['filename']="head.htm";
$z[3]=Array("channel","	\r\n                    <li class=\"col-xs-4\">\r\n                        <a href=\"[field:typelink/]\">[field:typename/]</a>\r\n                    </li>\r\n                 ",1302,1540);
$z[3][4]['row']="4";
$z[3][4]['typeid']="2";
$z[4]=Array("list","\r\n						<li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                         ",1830,1955);
$z[4][4]['pagesize']="8";
$z[5]=Array("pagelist","",2255,2336);
$z[5][4]['listitem']="info,index,end,pre,next,pageno,option";
$z[5][4]['listsize']="3";
$z[6]=Array("include","",2763,2800);
$z[6][4]['filename']="footer.htm";

?>